source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

use_frameworks!
pod 'Alamofire', '~> 1.2'

use_frameworks!
pod 'SwiftyJSON', '~> 2.2.0'


use_frameworks!
pod 'SQLite.swift', git: 'https://github.com/stephencelis/SQLite.swift.git'